# .github/workflows/android.yml
name: Android CI
permissions:
  contents: read
  actions: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> local.properties
          echo "${{ secrets.SIGN_JKS }}" | base64 -d > sign.jks
          echo "KEYSTORE_FILE=../sign.jks" >> local.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Build APK
        run: ./gradlew assembleRelease --parallel

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest --parallel

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testReleaseUnitTest/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-